services:
  postgres:
    image: postgres:latest
    container_name: hotelDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hotel
    ports:
      - "5444:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  hotel:
    container_name: hotel
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hotel
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - mynetwork

  comments:
    container_name: comments
    build:
      context: ../comments
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/comments
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - mynetwork

  authentication:
    container_name: authentication
    build:
      context: ../authentication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentication
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - mynetwork

  bff:
    container_name: bff
    build:
      context: ../bff
      dockerfile: Dockerfile
    environment:
      - hotel.url=http://hotel:8081
      - comments.url=http://comments:8082
      - authentication.url=http://authentication:8083
    ports:
      - "8084:8084"
    depends_on:
      - hotel
      - comments
      - authentication
      - postgres
    networks:
      - mynetwork

volumes:
  db:

networks:
  mynetwork:
    driver: bridge